# Generated by Django 4.1.2 on 2022-10-24 00:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=100, null=True)),
                ('imageType', models.CharField(blank=True, max_length=20, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('missedIngredientCount', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('usedIngredientCount', models.IntegerField(blank=True, null=True)),
                ('missedIngredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None)),
                ('unusedIngredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None)),
                ('usedIngredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), size=None)),
            ],
        ),
    ]
