# Generated by Django 4.1.2 on 2022-10-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipe_id_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_id',
            name='license',
        ),
    ]
